In [1]:
# !pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([12, 34, 56, 78, 20])

In [4]:
a

array([12, 34, 56, 78, 20])

In [5]:
print(a)

[12 34 56 78 20]


In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(5,)

In [8]:
a.ndim

1

In [9]:
b = np.array([12, 34, 11.23, True, "Ranjit"])

In [10]:
b

array(['12', '34', '11.23', 'True', 'Ranjit'], dtype='<U32')

In [11]:
b.dtype

dtype('<U32')

In [12]:
c = np.array([23, 45, 67, 9.32, 10])

In [13]:
c.dtype

dtype('float64')

In [14]:
a

array([12, 34, 56, 78, 20])

In [15]:
a * 2

array([ 24,  68, 112, 156,  40])

In [16]:
# speed test

In [17]:
values = 1000000

list1 = list(range(values))
arr1 = np.array(list1)

In [18]:
import time

In [19]:
time.time()

1744304866.786178

In [20]:
start_time = time.time()
newl = [i * 2 for i in list1]
final_time1 = time.time() - start_time
print(f"time taken by the list is -> {final_time1}")

time taken by the list is -> 0.021358251571655273


In [21]:
start_time = time.time()
newarr = arr1 * 2
final_time2 = time.time() - start_time
print(f"time taken by the array is -> {final_time2}")

time taken by the array is -> 0.0019683837890625


In [22]:
final_time1/final_time2

10.850654069767442

In [23]:
# arange

In [24]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.arange(5, 21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
# 2d arrays

In [30]:
arr = np.array([[1, 3, 4], [12, 5, 6], [2, 5, 4], [5, 7, 2]])

In [31]:
arr

array([[ 1,  3,  4],
       [12,  5,  6],
       [ 2,  5,  4],
       [ 5,  7,  2]])

In [32]:
arr.shape

(4, 3)

In [33]:
arr.size

12

In [34]:
arr.ndim

2

In [35]:
arr.flatten()

array([ 1,  3,  4, 12,  5,  6,  2,  5,  4,  5,  7,  2])

In [36]:
arr.reshape(3, 4)

array([[ 1,  3,  4, 12],
       [ 5,  6,  2,  5],
       [ 4,  5,  7,  2]])

In [37]:
arr.reshape(2, 6)

array([[ 1,  3,  4, 12,  5,  6],
       [ 2,  5,  4,  5,  7,  2]])

In [38]:
arr.reshape(3, 2, 2)

array([[[ 1,  3],
        [ 4, 12]],

       [[ 5,  6],
        [ 2,  5]],

       [[ 4,  5],
        [ 7,  2]]])

In [39]:
arr.reshape(3, 2, 2).ndim

3

In [40]:
arr.reshape(2, -1)

array([[ 1,  3,  4, 12,  5,  6],
       [ 2,  5,  4,  5,  7,  2]])

In [41]:
arr.reshape(4, 3, -1)

array([[[ 1],
        [ 3],
        [ 4]],

       [[12],
        [ 5],
        [ 6]],

       [[ 2],
        [ 5],
        [ 4]],

       [[ 5],
        [ 7],
        [ 2]]])

In [42]:
arr

array([[ 1,  3,  4],
       [12,  5,  6],
       [ 2,  5,  4],
       [ 5,  7,  2]])

In [43]:
arr[1:3, 0:2]

array([[12,  5],
       [ 2,  5]])

In [44]:
arr[1:, 1:]

array([[5, 6],
       [5, 4],
       [7, 2]])

In [45]:
arr[:,:]

array([[ 1,  3,  4],
       [12,  5,  6],
       [ 2,  5,  4],
       [ 5,  7,  2]])

## linalg

In [94]:
arr1 = np.array([[1, 2, 3], [4, 6, 1], [9, 5, 4]])

In [96]:
arr1

array([[1, 2, 3],
       [4, 6, 1],
       [9, 5, 4]])

In [98]:
np.linalg.det(arr1)

-97.0

In [102]:
np.linalg.inv(arr1)

array([[-0.19587629, -0.07216495,  0.16494845],
       [ 0.07216495,  0.2371134 , -0.11340206],
       [ 0.35051546, -0.13402062,  0.02061856]])

In [106]:
arr2 = np.array([[1, 2], [4, 3]])
arr3 = np.array([[5, 10], [1, 1]])

In [110]:
arr2 @ arr3

array([[ 7, 12],
       [23, 43]])

In [112]:
np.linalg.eig(arr2)

EigResult(eigenvalues=array([-1.,  5.]), eigenvectors=array([[-0.70710678, -0.4472136 ],
       [ 0.70710678, -0.89442719]]))